export const ALL_CLIENT_REQUEST = "ALL_CLIENT_REQUEST";
export const ALL_CLIENT_SUCCESS = "ALL_CLIENT_SUCCESS";
export const ALL_CLIENT_FAIL = "ALL_CLIENT_FAIL";

export const CLIENT_DETAILS_REQUEST = "CLIENT_DETAILS_REQUEST";
export const CLIENT_DETAILS_SUCCESS = "CLIENT_DETAILS_SUCCESS";
export const CLIENT_DETAILS_FAIL = "CLIENT_DETAILS_FAIL";

export const NEW_CLIENT_REQUEST = "NEW_CLIENT_REQUEST";
export const NEW_CLIENT_SUCCESS = "NEW_CLIENT_SUCCESS";
export const NEW_CLIENT_FAIL = "NEW_CLIENT_FAIL";
export const NEW_CLIENT_RESET = "NEW_CLIENT_RESET";

export const LOGIN_CLIENT_REQUEST = "LOGIN_CLIENT_REQUEST";
export const LOGIN_CLIENT_SUCCESS = "LOGIN_CLIENT_SUCCESS";
export const LOGIN_CLIENT_FAIL = "LOGIN_CLIENT_FAIL";

export const LOGOUT_CLIENT_REQUEST = "LOGOUT_CLIENT_REQUEST";
export const LOGOUT_CLIENT_SUCCESS = "LOGOUT_CLIENT_SUCCESS";
export const LOGOUT_CLIENT_FAIL = "LOGOUT_CLIENT_FAIL";

export const LOAD_CLIENT_REQUEST = "LOAD_CLIENT_REQUEST";
export const LOAD_CLIENT_SUCCESS = "LOAD_CLIENT_SUCCESS";
export const LOAD_CLIENT_FAIL = "LOAD_CLIENT_FAIL";

export const ADMIN_CLIENT_REQUEST = "ADMIN_CLIENT_REQUEST";
export const ADMIN_CLIENT_SUCCESS = "ADMIN_CLIENT_SUCCESS";
export const ADMIN_CLIENT_FAIL = "ADMIN_CLIENT_FAIL";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";
export const DELETE_CLIENT_RESET = "DELETE_CLIENT_RESET";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAIL = "UPDATE_CLIENT_FAIL";
export const UPDATE_CLIENT_RESET = "UPDATE_CLIENT_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";