export const ALL_INVOICE_REQUEST = "ALL_INVOICE_REQUEST";
export const ALL_INVOICE_SUCCESS = "ALL_INVOICE_SUCCESS";
export const ALL_INVOICE_FAIL = "ALL_INVOICE_FAIL";

export const INVOICE_DETAILS_REQUEST = "INVOICE_DETAILS_REQUEST";
export const INVOICE_DETAILS_SUCCESS = "INVOICE_DETAILS_SUCCESS";
export const INVOICE_DETAILS_FAIL = "INVOICE_DETAILS_FAIL";

export const NEW_INVOICE_REQUEST = "NEW_INVOICE_REQUEST";
export const NEW_INVOICE_SUCCESS = "NEW_INVOICE_SUCCESS";
export const NEW_INVOICE_FAIL = "NEW_INVOICE_FAIL";
export const NEW_INVOICE_RESET = "NEW_INVOICE_RESET";

export const ADMIN_INVOICE_REQUEST = "ADMIN_INVOICE_REQUEST";
export const ADMIN_INVOICE_SUCCESS = "ADMIN_INVOICE_SUCCESS";
export const ADMIN_INVOICE_FAIL = "ADMIN_INVOICE_FAIL";

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";
export const DELETE_INVOICE_RESET = "DELETE_INVOICE_RESET";

export const UPDATE_INVOICE_REQUEST = "UPDATE_INVOICE_REQUEST";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAIL = "UPDATE_INVOICE_FAIL";
export const UPDATE_INVOICE_RESET = "UPDATE_INVOICE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";