export const LOGIN_MEMBER_REQUEST = "LOGIN_MEMBER_REQUEST";
export const LOGIN_MEMBER_SUCCESS = "LOGIN_MEMBER_SUCCESS";
export const LOGIN_MEMBER_FAIL = "LOGIN_MEMBER_FAIL";

export const LOGOUT_MEMBER_REQUEST = "LOGOUT_MEMBER_REQUEST";
export const LOGOUT_MEMBER_SUCCESS = "LOGOUT_MEMBER_SUCCESS";
export const LOGOUT_MEMBER_FAIL = "LOGOUT_MEMBER_FAIL";

export const LOAD_MEMBER_REQUEST = "LOAD_MEMBER_REQUEST";
export const LOAD_MEMBER_SUCCESS = "LOAD_MEMBER_SUCCESS";
export const LOAD_MEMBER_FAIL = "LOAD_MEMBER_FAIL";

export const ALL_COMBINED_REQUEST = "ALL_COMBINED_REQUEST";
export const ALL_COMBINED_SUCCESS = "ALL_COMBINED_SUCCESS";
export const ALL_COMBINED_FAIL = "ALL_COMBINED_FAIL";

export const ADMIN_COMBINED_REQUEST = "ADMIN_COMBINED_REQUEST";
export const ADMIN_COMBINED_SUCCESS = "ADMIN_COMBINED_SUCCESS";
export const ADMIN_COMBINED_FAIL = "ADMIN_COMBINED_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_USER_ROLE = "SET_USER_ROLE";

export const ENTER_TEAM_DETAILS_SUCCESS= 'ENTER_TEAM_DETAILS_SUCCESS'
export const ENTER_TEAM_DETAILS_FAILURE = 'ENTER_TEAM_DETAILS_FAILURE'


export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';


export const UPDATE_LOGGED_IN_USER =  'UPDATE_LOGGED_IN_USER';

