export const ALL_QUOTE_REQUEST = "ALL_QUOTE_REQUEST";
export const ALL_QUOTE_SUCCESS = "ALL_QUOTE_SUCCESS";
export const ALL_QUOTE_FAIL = "ALL_QUOTE_FAIL";

export const QUOTE_DETAILS_REQUEST = "QUOTE_DETAILS_REQUEST";
export const QUOTE_DETAILS_SUCCESS = "QUOTE_DETAILS_SUCCESS";
export const QUOTE_DETAILS_FAIL = "QUOTE_DETAILS_FAIL";

export const NEW_QUOTE_REQUEST = "NEW_QUOTE_REQUEST";
export const NEW_QUOTE_SUCCESS = "NEW_QUOTE_SUCCESS";
export const NEW_QUOTE_FAIL = "NEW_QUOTE_FAIL";
export const NEW_QUOTE_RESET = "NEW_QUOTE_RESET";


export const ADMIN_QUOTE_REQUEST = "ADMIN_QUOTE_REQUEST";
export const ADMIN_QUOTE_SUCCESS = "ADMIN_QUOTE_SUCCESS";
export const ADMIN_QUOTE_FAIL = "ADMIN_QUOTE_FAIL";

export const DELETE_QUOTE_REQUEST = "DELETE_QUOTE_REQUEST";
export const DELETE_QUOTE_SUCCESS = "DELETE_QUOTE_SUCCESS";
export const DELETE_QUOTE_FAIL = "DELETE_QUOTE_FAIL";
export const DELETE_QUOTE_RESET = "DELETE_QUOTE_RESET";

export const UPDATE_QUOTE_REQUEST = "UPDATE_QUOTE_REQUEST";
export const UPDATE_QUOTE_SUCCESS = "UPDATE_QUOTE_SUCCESS";
export const UPDATE_QUOTE_FAIL = "UPDATE_QUOTE_FAIL";
export const UPDATE_QUOTE_RESET = "UPDATE_QUOTE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";