export const ALL_TASK_COMMENT_REQUEST = "ALL_TASK_COMMENT_REQUEST";
export const ALL_TASK_COMMENT_SUCCESS = "ALL_TASK_COMMENT_SUCCESS";
export const ALL_TASK_COMMENT_FAIL = "ALL_TASK_COMMENT_FAIL";

export const TASK_COMMENT_DETAILS_REQUEST = "TASK_COMMENT_DETAILS_REQUEST";
export const TASK_COMMENT_DETAILS_SUCCESS = "TASK_COMMENT_DETAILS_SUCCESS";
export const TASK_COMMENT_DETAILS_FAIL = "TASK_COMMENT_DETAILS_FAIL";

export const NEW_TASK_COMMENT_REQUEST = "NEW_TASK_COMMENT_REQUEST";
export const NEW_TASK_COMMENT_SUCCESS = "NEW_TASK_COMMENT_SUCCESS";
export const NEW_TASK_COMMENT_FAIL = "NEW_TASK_COMMENT_FAIL";
export const NEW_TASK_COMMENT_RESET = "NEW_TASK_COMMENT_RESET";

export const ADMIN_TASK_COMMENT_REQUEST = "ADMIN_TASK_COMMENT_REQUEST";
export const ADMIN_TASK_COMMENT_SUCCESS = "ADMIN_TASK_COMMENT_SUCCESS";
export const ADMIN_TASK_COMMENT_FAIL = "ADMIN_TASK_COMMENT_FAIL";

export const DELETE_TASK_COMMENT_REQUEST = "DELETE_TASK_COMMENT_REQUEST";
export const DELETE_TASK_COMMENT_SUCCESS = "DELETE_TASK_COMMENT_SUCCESS";
export const DELETE_TASK_COMMENT_FAIL = "DELETE_TASK_COMMENT_FAIL";
export const DELETE_TASK_COMMENT_RESET = "DELETE_TASK_COMMENT_RESET";

export const UPDATE_TASK_COMMENT_REQUEST = "UPDATE_TASK_COMMENT_REQUEST";
export const UPDATE_TASK_COMMENT_SUCCESS = "UPDATE_TASK_COMMENT_SUCCESS";
export const UPDATE_TASK_COMMENT_FAIL = "UPDATE_TASK_COMMENT_FAIL";
export const UPDATE_TASK_COMMENT_RESET = "UPDATE_TASK_COMMENT_RESET";

export const DELETE_SUBTASK_REQUEST = 'DELETE_SUBTASK_REQUEST';
export const DELETE_SUBTASK_SUCCESS = 'DELETE_SUBTASK_SUCCESS';
export const DELETE_SUBTASK_FAIL = 'DELETE_SUBTASK_FAIL';
export const DELETE_SUBTASK_RESET = 'DELETE_SUBTASK_RESET';


export const DELETE_ATTACHMENT_REQUEST = 'DELETE_ATTACHMENT_REQUEST';
export const DELETE_ATTACHMENT_SUCCESS = 'DELETE_ATTACHMENT_SUCCESS';
export const DELETE_ATTACHMENT_FAIL = 'DELETE_ATTACHMENT_FAIL';
export const DELETE_ATTACHMENT_RESET = 'DELETE_ATTACHMENT_RESET';


export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET';


export const UPDATE_SUBTASK_REQUEST = 'UPDATE_SUBTASK_REQUEST';
export const UPDATE_SUBTASK_SUCCESS = 'UPDATE_SUBTASK_SUCCESS';
export const UPDATE_SUBTASK_FAIL = 'UPDATE_SUBTASK_FAIL';
export const UPDATE_SUBTASK_RESET = 'UPDATE_SUBTASK_RESET';


export const UPDATE_ATTACHMENT_REQUEST = 'UPDATE_ATTACHMENT_REQUEST';
export const UPDATE_ATTACHMENT_SUCCESS = 'UPDATE_ATTACHMENT_SUCCESS';
export const UPDATE_ATTACHMENT_FAIL = 'UPDATE_ATTACHMENT_FAIL';
export const UPDATE_ATTACHMENT_RESET = 'UPDATE_ATTACHMENT_RESET';


export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';
export const UPDATE_COMMENT_RESET = 'UPDATE_COMMENT_RESET';

export const ADD_EMOJI_REACTION_REQUEST = "ADD_EMOJI_REACTION_REQUEST";
export const ADD_EMOJI_REACTION_SUCCESS = "ADD_EMOJI_REACTION_SUCCESS";
export const ADD_EMOJI_REACTION_FAIL = "ADD_EMOJI_REACTION_FAIL";
export const ADD_EMOJI_REACTION_RESET = "ADD_EMOJI_REACTION_RESET";



export const CREATE_SUBTASK_REQUEST = 'CREATE_SUBTASK_REQUEST';
export const CREATE_SUBTASK_SUCCESS = 'CREATE_SUBTASK_SUCCESS';
export const CREATE_SUBTASK_FAIL    = 'CREATE_SUBTASK_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";